import type { Metadata } from 'next';
import { site } from '@/content/site';

/**
 * ONE owner for public URL format, page metadata and JSON-LD serialisation.
 *
 * next.config.ts sets `trailingSlash: true`, so the export writes
 * out/about/index.html and the canonical, production URL is
 * `https://dreamweaversoffice.com/about/`. The sitemap already emitted that
 * form, but page metadata declared `/about` — canonical, sitemap and the URL a
 * crawler actually lands on disagreed on every route. Anything that emits a
 * site URL must go through here so that cannot drift again.
 */

/**
 * The origin this build will actually be served from.
 *
 * `site.domain` is where the site will LIVE, not where a given build is
 * reachable today. Pinning every absolute URL to it meant the Netlify staging
 * deploy advertised `og:image` as
 * https://dreamweaversoffice.com/img/og-cover.png — the client's current live
 * site, which has no such file. WhatsApp and every other Open Graph consumer
 * fetched that URL, got a 404, and rendered the share with no card at all.
 * The image was fine; nothing pointed at it.
 *
 * Netlify sets DEPLOY_PRIME_URL at build time (the branch subdomain for a
 * preview; the site's primary URL for the production context), so once the
 * custom domain is attached this resolves to site.domain on its own and the
 * override disappears without an edit here.
 *
 * EVERY CANDIDATE IS VALIDATED, because one of them arrived malformed in
 * practice. Netlify builds the branch subdomain by splicing the git branch
 * name in front of the site name and does not sanitise it, so branch
 * `build/dreamweavers-portfolio` produced
 *
 *   https://build/dreamweavers-portfolio--dreamweavers-office.netlify.app
 *
 * whose host is `build` and whose path is the rest. That is a well-formed URL
 * — `new URL()` accepts it — so only a check that the origin has a dotted
 * host AND no path catches it. Unvalidated, it shipped an og:image that did
 * not even resolve in DNS, which is worse than the 404 this set out to fix.
 *
 * NEXT_PUBLIC_SITE_URL takes precedence for hosts that publish no such
 * variable; URL is Netlify's stable primary site URL, used when the
 * deploy-specific one is unusable. With none set — a local build, and
 * therefore every test — this falls back to site.domain, so nothing about
 * local output changes.
 */
function usableOrigin(value: string | undefined): string | null {
  if (!value) return null;
  let url: URL;
  try {
    url = new URL(value);
  } catch {
    return null;
  }
  if (url.protocol !== 'https:' && url.protocol !== 'http:') return null;
  // A bare origin only: a dotted host, and nothing in the path.
  if (!url.hostname.includes('.')) return null;
  if (url.pathname !== '/') return null;
  return url.origin;
}

const BASE =
  usableOrigin(process.env.NEXT_PUBLIC_SITE_URL) ??
  usableOrigin(process.env.DEPLOY_PRIME_URL) ??
  usableOrigin(process.env.URL) ??
  site.domain.replace(/\/+$/, '');

/**
 * The resolved origin, for the two places that cannot go through
 * absoluteUrl(): `metadataBase`, which Next resolves every RELATIVE metadata
 * URL against — including the social image — and robots.txt.
 */
export const SITE_URL = BASE;

/**
 * Whether this build is being served from the real domain.
 *
 * A staging build now emits self-referencing canonicals, which is correct for
 * sharing but would let the Netlify subdomain compete with production in the
 * index. app/layout.tsx reads this to mark non-production builds noindex.
 *
 * Deliberately NOT enforced through robots.txt: `Disallow: /` would also stop
 * facebookexternalhit — the crawler WhatsApp and Facebook share this with —
 * from fetching the page, which is the exact breakage this change exists to
 * fix. `noindex` keeps the page fetchable and keeps it out of search.
 */
export const IS_CANONICAL_HOST = BASE === site.domain.replace(/\/+$/, '');

/** Leading slash, exactly one trailing slash, no double slashes. */
export function canonicalPath(path: string): string {
  const trimmed = path.replace(/^\/+/, '').replace(/\/+$/, '');
  return trimmed === '' ? '/' : `/${trimmed}/`;
}

/** Absolute production URL for a route. */
export function absoluteUrl(path: string): string {
  return `${BASE}${canonicalPath(path)}`;
}

/**
 * The social preview card. 1200x630 is the size Open Graph consumers crop to
 * and the size `summary_large_image` expects; the previous build advertised
 * the 420x320 logo, which those consumers letterbox or reject.
 *
 * Generated by scripts/make-og.mjs from the existing logo and brand tokens —
 * it asserts nothing the site does not already say.
 */
export const SOCIAL_IMAGE = {
  url: '/img/og-cover.png',
  width: 1200,
  height: 630,
} as const;

type PageMetaInput = {
  /** Page title WITHOUT the site suffix; the root template adds it. */
  title: string;
  description: string;
  /** Route path, e.g. '/services/web-development'. */
  path: string;
  /** Defaults to the site social card. */
  image?: { url: string; width: number; height: number };
  /** Thin pages that should be crawled but not indexed. */
  noindex?: boolean;
};

/**
 * Per-page metadata, built only from copy that already exists on the page.
 *
 * Child pages previously set title/description/canonical and nothing else, so
 * they inherited the root Open Graph and Twitter blocks wholesale: every share
 * of every page showed the homepage's card.
 */
export function pageMetadata({
  title,
  description,
  path,
  image = SOCIAL_IMAGE,
  noindex = false,
}: PageMetaInput): Metadata {
  const url = absoluteUrl(path);
  // Mirrors the root title template so the share card matches the tab.
  const social = path === '/' ? title : `${title} | ${site.name}`;
  const images = [{ url: image.url, width: image.width, height: image.height, alt: site.name }];

  return {
    title,
    description,
    alternates: { canonical: canonicalPath(path) },
    ...(noindex ? { robots: { index: false, follow: true } } : {}),
    openGraph: {
      type: 'website',
      siteName: site.name,
      locale: 'en_US',
      title: social,
      description,
      url,
      images,
    },
    twitter: {
      card: 'summary_large_image',
      title: social,
      description,
      images: [image.url],
    },
  };
}

/**
 * Serialises JSON-LD for `dangerouslySetInnerHTML`.
 *
 * Escaping `<` means a value can never close the surrounding <script> tag.
 * Today every value is local, controlled content, so this is defence against
 * a future author wiring in something that is not.
 */
export function jsonLd(schema: unknown): string {
  return JSON.stringify(schema).replace(/</g, '\\u003c');
}

/** Stable identity for the organisation, referenced by other schema nodes. */
export const ORGANIZATION_ID = `${BASE}/#organization`;

/** BreadcrumbList from an ordered trail. URLs run through the same helper. */
export function breadcrumbSchema(trail: { name: string; path: string }[]) {
  return {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: trail.map((crumb, i) => ({
      '@type': 'ListItem',
      position: i + 1,
      name: crumb.name,
      item: absoluteUrl(crumb.path),
    })),
  };
}
